---
title: "UK - K Nearest"
author: "Author_Name"
date: "5/21/2021"
output: html_document
---

## K nearest neighbour (using normalized data)
#### Split data (70-30)
```{r}

set.seed(17245)
sample_data <- createDataPartition(sampled_normalized$Accident_Severity, p=0.7, list=FALSE) 
train_sample_normalized <- sampled_normalized[sample_data, ]
test_sample_normalized <- sampled_normalized[-sample_data, ]
```

#### Get accuracy baseline
```{r}

accuracybasline <- round(length(test_sample_normalized[test_sample_normalized$Accident_Severity == 'Slight', ]$Accident_Severity)/
                             length(test_sample_normalized$Accident_Severity), 3)
accuracybasline
```

### Training the Model
```{r}
start_time <- Sys.time()
knnFit <- train(Accident_Severity~., data=train_sample_normalized, method="knn", tuneGrid=expand.grid(k=25:50),
                metric="Accuracy", trControl=trainControl(method="cv", number=10))
end_time <- Sys.time()
knn_runtime <- round(as.numeric(end_time - start_time), 2)
plot(knnFit)

```

### Testing the Model
```{r}

test_sample_normalized$Accident_Severity = as.factor(test_sample_normalized$Accident_Severity)

test_sample_normalized$pred <- predict(knnFit, test_sample_normalized)
knn_confusion_mtx <- confusionMatrix(data=test_sample_normalized$pred, reference=test_sample_normalized$Accident_Severity)
test_sample_normalized <- test_sample_normalized %>%
  mutate(pred = predict(knnFit, test_sample_normalized),
         pred_prob = predict(knnFit, type="prob", test_sample_normalized)[,2],
         error = ifelse(pred != Accident_Severity, 1, 0))

#Roc
roc <- test_sample_normalized %>%
  select(Accident_Severity, pred_prob) %>%
  mutate(Accident_Severity = as.numeric(Accident_Severity) - 1,
         Accident_Severity.str = c("Fatal_Serious", "Slight")[Accident_Severity + 1]) %>%
  ggplot(aes(d = Accident_Severity, m = pred_prob)) +
  geom_roc(labels = FALSE)
roc +
  style_roc(theme = theme_bw, xlab = "False Positive Rate", ylab = "True Positive Rate") +
  theme(panel.grid.major = element_blank(), panel.border = element_blank(),
        axis.line = element_line(colour = "grey")) +
  ggtitle("kNN - ROC Curve") +
  annotate("text", x = .75, y = .25,
           label = paste("AUROC =", round(calc_auc(roc)$AUC, 3)))

```

### Model Evaluation
```{r}
knn_accuracy <- round(knn_confusion_mtx$overall['Accuracy'], 3)
knn_recall <- round(knn_confusion_mtx$byClass['Sensitivity'], 3)
knn_precision <- round(knn_confusion_mtx$byClass['Pos Pred Value'], 3)
knn_f1_score <- round(2*((knn_precision * knn_recall) / (knn_precision + knn_recall)), 3)
knn_roc <- round(calc_auc(roc)$AUC, 3)
test_sample_normalized <- test_sample_normalized[ , !(names(test_sample_normalized) %in% c('pred', 'pred_prob', 'error'))]
data.frame(accuracybasline, knn_accuracy, knn_recall, knn_precision, knn_f1_score, knn_roc)
```
